// (c) Copyright Microsoft Corporation.
// This source is subject to the Microsoft Public License (Ms-PL).
// Please see http://go.microsoft.com/fwlink/?LinkID=131993 for details.
// All other rights reserved.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames", Justification = "Unofficial release.")]

[assembly: SuppressMessage("General", "SWC1001:XmlDocumentationCommentShouldBeSpelledCorrectly", MessageId = "Polyline", Justification = "Matches System.Windows.Shapes.Polyline.")]
[assembly: SuppressMessage("General", "SWC1001:XmlDocumentationCommentShouldBeSpelledCorrectly", MessageId = "Intelli", Justification = "Part of IntelliSense.")]
[assembly: SuppressMessage("General", "SWC1001:XmlDocumentationCommentShouldBeSpelledCorrectly", MessageId = "Silverlight", Justification = "Product name.")]
[assembly: SuppressMessage("General", "SWC1001:XmlDocumentationCommentShouldBeSpelledCorrectly", MessageId = "tuple's", Justification = "Consistent with MSDN documentation for .NET 4.")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.ActualMaximum")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.ActualMinimum")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.GetPlotAreaCoordinate(System.IComparable)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.RangeChanged(Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxisInformationProvider,Pixytech.Desktop.Presentation.DataVisualization.Range`1<System.IComparable>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.GetPlotAreaCoordinateValueRange(System.Double)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.ICategoryAxisInformationProvider.GetCategories(Pixytech.Desktop.Presentation.DataVisualization.Charting.ICategoryAxis)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxisInformationProvider.GetActualRange(Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxisInformationProvider.GetDesiredRange(Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxis.Register(System.Object)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxis.Unregister(System.Object)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis.Range")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxisListener.AxisInvalidated(Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxis)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IDataProvider.GetData(Pixytech.Desktop.Presentation.DataVisualization.Charting.IDataConsumer)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeProvider.GetRange(Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeConsumer)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.CollectionBase`1.#System.Collections.ICollection.SyncRoot")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.CollectionBase`1.#System.Collections.Generic.ICollection`1<!0>.IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.ListBaseCollection`1.#System.Collections.IList.IsFixedSize")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.ListBaseCollection`1.#System.Collections.IList.IsReadOnly")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.CollectionBase`1.#System.Collections.ICollection.IsSynchronized")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ColumnBarBaseSeries`1.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IAnchoredToOrigin.AnchoredAxis")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeConsumer.RangeChanged(Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeProvider,Pixytech.Desktop.Presentation.DataVisualization.Range`1<System.IComparable>)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis.#Pixytech.Desktop.Presentation.DataVisualization.Charting.IValueMarginConsumer.ValueMarginsChanged(Pixytech.Desktop.Presentation.DataVisualization.Charting.IValueMarginProvider,System.Collections.Generic.IEnumerable`1<Pixytech.Desktop.Presentation.DataVisualization.Charting.ValueMargin>)")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.PieSeries.#.cctor()")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "XamlGeneratedNamespace")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors", Scope = "member", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.SeriesHostAxesCollection.#.ctor(Pixytech.Desktop.Presentation.DataVisualization.Charting.ISeriesHost)")]
[assembly: SuppressMessage("Microsoft.Design", "CA1020:AvoidNamespacesWithFewTypes", Scope = "namespace", Target = "Pixytech.Desktop.Presentation.DataVisualization.Charting.Primitives")]

// Suppress "Silverlight-only class or assembly" warning for all DataVisualization classes because there is currently no corresponding WPF implementation.
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.AnimationSequence")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.ChartingLabel")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.ChartingLocation")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.ChartingOrientation")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.BarDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.BarSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.BubbleDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.BubbleSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.CategoryAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.CategorySortOrder")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.Chart")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ColumnDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ColumnSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSeriesWithAxes")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointSingleSeriesWithAxes")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DataPointState")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DateTimeAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DateTimeAxisLabel")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DateTimeIntervalType")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxisGridLinesElementProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ICategoryAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ICategoryAxisInformationProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeAxisInformationProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRequireGlobalSeriesIndex")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ISeriesHost")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.LegendItem")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.LineDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.LineSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.LinearAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.NumericAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.NumericAxisLabel")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.PieDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.PieSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RangeAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ScatterDataPoint")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ScatterSeries")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.Series")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.IStyleDispenser")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Legend")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Range`1")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.StringFormatConverter")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.ResourceDictionaryCollection")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Title")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ColumnBarBaseSeries`1")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.DisplayAxis")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IAnnotationProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IAxisListener")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IDataConsumer")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IDataProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeConsumer")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRangeProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IRequireSeriesHost")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IScrollService")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IValueMarginConsumer")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.IValueMarginProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.PointOrientedPanel")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.RadialPanel")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.ValueMargin")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.IScrollServiceInformationProvider")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Unit")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.UnitValue")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.ListBaseCollection`1")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.CollectionBase`1")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.Primitives.Edge")]
[assembly: SuppressMessage("Compatibility", "SWC4000:GeneralWPFCompatibilityRule", MessageId = "Pixytech.Desktop.Presentation.DataVisualization.Charting.Primitives.EdgePanel")]
