//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixytech.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixytech.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;&apos;{0}&apos; cannot be an empty string (&quot;&quot;).&quot;.
        /// </summary>
        internal static string ArgumentException_EmptyString {
            get {
                return ResourceManager.GetString("ArgumentException_EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @&quot;The type of &apos;{0}&apos; is not supported as an argument.&quot;.
        /// </summary>
        internal static string ArgumentException_Type {
            get {
                return ResourceManager.GetString("ArgumentException_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use the UIThread option for subscribing, the EventAggregator must be constructed on the UI thread..
        /// </summary>
        internal static string EventAggregatorNotConstructedOnUIThread {
            get {
                return ResourceManager.GetString("EventAggregatorNotConstructedOnUIThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Conversion delegate must take one parameter..
        /// </summary>
        internal static string Exception_ConversionTakesOneParameter {
            get {
                return ResourceManager.GetString("Exception_ConversionTakesOneParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The type &apos;{0}&apos; does not match any known middleware pattern..
        /// </summary>
        internal static string Exception_MiddlewareNotSupported {
            get {
                return ResourceManager.GetString("Exception_MiddlewareNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  The class &apos;{0}&apos; does not have a constructor taking {1} arguments..
        /// </summary>
        internal static string Exception_NoConstructorFound {
            get {
                return ResourceManager.GetString("Exception_NoConstructorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  No conversion available between {0} and {1}..
        /// </summary>
        internal static string Exception_NoConversionExists {
            get {
                return ResourceManager.GetString("Exception_NoConversionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Delegate Reference Type Exception.
        /// </summary>
        internal static string InvalidDelegateRerefenceTypeException {
            get {
                return ResourceManager.GetString("InvalidDelegateRerefenceTypeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity does not contain a property with that name.
        /// </summary>
        internal static string InvalidPropertyNameException {
            get {
                return ResourceManager.GetString("InvalidPropertyNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid expression.
        /// </summary>
        internal static string PropertySupport_ExtractPropertyName_Invalid_expression {
            get {
                return ResourceManager.GetString("PropertySupport_ExtractPropertyName_Invalid_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument passed contains more than a single dot which is not allowed: .
        /// </summary>
        internal static string Reflect_GetMemberInfo_Argument_passed_contains_more_than_a_single_dot_which_is_not_allowed__ {
            get {
                return ResourceManager.GetString("Reflect_GetMemberInfo_Argument_passed_contains_more_than_a_single_dot_which_is_no" +
                        "t_allowed__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a lambda expression.
        /// </summary>
        internal static string Reflect_GetMemberInfo_Not_a_lambda_expression {
            get {
                return ResourceManager.GetString("Reflect_GetMemberInfo_Not_a_lambda_expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member access.
        /// </summary>
        internal static string Reflect_GetMemberInfo_Not_a_member_access {
            get {
                return ResourceManager.GetString("Reflect_GetMemberInfo_Not_a_member_access", resourceCulture);
            }
        }
    }
}
